services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./common/sql/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10  # Увеличим количество попыток
      start_period: 30s  # Дадим базе больше времени на запуск
    restart: unless-stopped
    ports:
      - "0.0.0.0:5433:5432"  # Важно: добавьте эту строку, если её нет

  redis:
    image: redis:7
    volumes:
      - redisdata:/data
    restart: unless-stopped

  reader:
    build:
      context: .
      dockerfile: reader/Dockerfile
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
