services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./common/sql/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redisdata:/data

  reader:
    image: ${DOCKERHUB_USERNAME}/reader:latest  # Используем образ из Docker Hub
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      db:
        condition: service_healthy

  bot:
    image: ${DOCKERHUB_USERNAME}/bot:latest  # Используем образ из Docker Hub
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  redisdata:
